config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :arduinos

  resources :data

  resources :sensor_types

  post 'sensors/compare' => 'sensors#compare'
  resources :sensors

  resources :hives

  devise_for :users #enable registration

  namespace :admin do
    get '', to: 'admin#index', as: '/'
    resources :users
  end

  scope '/admin' do
    get 'sensors' => 'sensors#index2'
    get 'hives' => 'hives#index2'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get '/:hive_name' => 'hives#show'

  root to: 'hives#index'

end

app/models/arduino.rb
class Arduino < ActiveRecord::Base
  has_many :sensors
  belongs_to :hive
  validates :name, :serial,  presence: true
  validates_uniqueness_of :name, scope: :hive
  validates_uniqueness_of :serial, scope: :hive
end

app/controllers/arduinos_controller.rb
# encoding: utf-8
class ArduinosController < ApplicationController
  load_and_authorize_resource
  before_action :set_arduinos, only: [:show, :edit, :update, :destroy]

  # GET /arduinos
  # GET /arduinos.json
  def index
    @arduino = Arduino.all
  end

  # GET /arduino/1
  # GET /arduino/1.json
  def show
  end

  # GET /arduinos/new
  def new
    @arduinos = Arduino.new
  end

  # GET /arduinos/1/edit
  def edit
  end

  # POST /arduinos
  # POST /arduinos.json
  def create
    @arduinos = Arduino.new(arduino_params)

    respond_to do |format|
      if @arduinos.save
        format.html { redirect_to :back, notice: 'Arduino créé avec succès.' }
        format.json { render :show, status: :created, location: @arduinos }
      else
        format.html { render :new }
        format.json { render json: @arduinos.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arduinos/1
  # PATCH/PUT /arduinos/1.json
  def update
    respond_to do |format|
      if @arduinos.update(arduino_params)
        format.html { redirect_to :back, notice: 'Arduino mise à jour avec succès.' }
        format.json { render :show, status: :ok, location: @arduinos }
      else
        format.html { render :edit }
        format.json { render json: @arduinos.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arduinos/1
  # DELETE /arduinos/1.json
  def destroy
    @arduinos.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Arduino suppirmée avec succès.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_arduinos
    @arduinos = Arduino.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def arduino_params
    params.require(:arduino).permit(:name, :hive_id, :serial)
  end
end

app/helpers/arduinos_helper.rb
module ArduinosHelper
end

app/views/arduinos/_form.html.erb
<%= bootstrap_form_for(@arduino) do |f| %>
    <%= f.text_field :name , label: "Nom"%>
    <% if(@arduino.hive_id.nil?) %>
        <%= f.select :hive_id, options_for_select(Hive.all.map{|s|[s.name, s.id]}), label: "Ruche" %>
    <% else %>
        <%= f.select :hive_id, options_for_select(Hive.all.map{|s|[s.name, s.id]}, @arduino.hive_id), label: "Ruche" %>
    <% end %>
    <%= f.number_field :serial, label: "Serial number"%>
    <%= f.submit %>
<% end %>

app/views/arduinos/edit.html.erb
<h1>Editer les arduinos</h1>

<%= render 'form' %>

<%= link_to 'Voir', @arduino %> |
<%= link_to 'Retour', :back %>

app/views/arduinos/index.html.erb
<h1>Listing arduinos</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hive</th>
      <th>Serial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arduinos.each do |arduino| %>
      <tr>
        <td><%= arduino.name %></td>
        <td><%= arduino.hive.name if arduino.hive %></td>
        <td><%= arduino.serial %></td>
        <td><%= link_to 'Voir', arduino %></td>
        <td><%= link_to 'Editer', edit_arduino_path(arduino) %></td>
        <td><%= link_to 'Supprimer', arduino, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle arduino', new_arduino_path %>

app/views/arduinos/new.html.erb
<h1>Nouvelle arduino</h1>

<%= render 'form' %>

<%= link_to 'Retour', arduinos_path %>

app/views/arduinos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @arduino.name %>
</p>

<p>
  <strong>Ruche:</strong>
  <%= @arduino.hive.name if @arduino.hive %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @arduino.serial %>
</p>

<%= link_to 'Editer', edit_arduino_path(@arduino) %> |
<%= link_to 'Retour', :back %>