config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :arduinos

  resources :data

  resources :sensor_types

  post 'sensors/compare' => 'sensors#compare'
  resources :sensors

  resources :hives

  devise_for :users #enable registration

  namespace :admin do
    get '', to: 'admin#index', as: '/'
    resources :users
  end

  scope '/admin' do
    get 'sensors' => 'sensors#index2'
    get 'hives' => 'hives#index2'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get '/:hive_name' => 'hives#show'

  root to: 'hives#index'

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
	belongs_to :arduino
	belongs_to :sensor_type
	has_many :datum
	validates :name, :serial,  presence: true
  validates_uniqueness_of :serial, scope: :arduino
end

app/models/sensor_type.rb
class SensorType < ActiveRecord::Base
	has_many :sensors
	validates :name, :unit, presence: true
	validates :name, uniqueness: true
	mount_uploader :image, ImagesUploader
end

app/controllers/sensors_controller.rb
# encoding: utf-8
class SensorsController < ApplicationController
  load_and_authorize_resource
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors_admin
  # GET /sensors_admin.json
  def index2
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @point = []
    if !params[:limit].nil? && params[:limit].to_i > 0
      @data = @sensor.datum.limit(params[:limit]).order('created_at DESC').all.reverse
      @data.each do |d|
        t = d.created_at.to_i * 1000
        @point.push([t, d.value.to_i])
      end
    else
      @data = @sensor.datum.all.order('created_at DESC').all.reverse
      @data.each do |d|
        t = d.created_at.to_i * 1000
        @point.push([t, d.value.to_i])
      end
    end
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title :text => @sensor.name
      f.series :name=>@sensor.sensor_type.name, :data=>@point, :color => '#ebbc14'
      f.xAxis :type => 'datetime', :maxZoom => 14 * 24 * 3600000 # fourteen days
      f.chart :zoomType => 'x'
      f.tooltip :valueSuffix => @sensor.sensor_type.unit
      f.yAxis  :title => {:text => @sensor.sensor_type.name + " (" + @sensor.sensor_type.unit + ")"}
      f.rangeSelector :enabled => 'true', :buttons => [{type:'week',count:1,text:'1s'},{type:'month',count:1,text:'1m'},{type:'month',count:6,text:'6m'},{type:'year',count:1,text:'1an'},{type:'all',text:'Tout'}],
      :buttonSpacing => 10, :inputDateFormat => '%e %b %Y', :inputEditDateFormat => '%d-%m-%Y'
      f.scrollbar :enabled => 'true', :minWidth => 30
    end
  end

  # GET /sensors/compare
  def compare
    sensorsList = params[:sensors]
    if !sensorsList.nil? and sensorsList.size > 0
      yAxis = []
      i = 0
      series = []
      sensorsList.each do |sensorId|
        point = []
        sensor = Sensor.find_by_id(sensorId)
          data = sensor.datum.all.order('created_at DESC').all.reverse
          data.each do |d|
            t = d.created_at.to_i * 1000
            point.push([t, d.value.to_i])
          end
        yAxis.push({:title => {:text => sensor.sensor_type.name + " (" + sensor.sensor_type.unit + ")"}})
        series.push({:name => sensor.name + ' (' + sensor.sensor_type.name + ')', :yAxis => i, :data => point, :tooltip => {:valueSuffix => sensor.sensor_type.unit}})
        i = i+1
      end

        @chart = LazyHighCharts::HighChart.new('graph') do |f|
          f.title :text => 'Comparaison'
          f.xAxis :type => 'datetime', :maxZoom => 14 * 24 * 3600000 # fourteen days
          f.chart :zoomType => 'x'
          series.each do |s|
            f.series(s)
          end
          f.yAxis yAxis
          f.rangeSelector :enabled => 'true', :buttons => [{type:'week',count:1,text:'1s'},{type:'month',count:1,text:'1m'},{type:'month',count:6,text:'6m'},{type:'year',count:1,text:'1an'},{type:'all',text:'Tout'}],
                          :buttonSpacing => 10, :inputDateFormat => '%e %b %Y', :inputEditDateFormat => '%d-%m-%Y'
          f.scrollbar :enabled => 'true', :minWidth => 30
        end
    else
      render Rails.application.routes.recognize_path(request.referer)[:action]
    end
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to :back, notice: 'Capteur créé avec succès.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to :back, notice: 'Capteur mis à jour avec succès.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Capteur supprimé avec succès.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sensor
    @sensor = Sensor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sensor_params
    params.require(:sensor).permit(:name, :sensor_type_id, :arduino_id, :serial)
  end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= bootstrap_form_for(@sensor) do |f| %>
    <%= f.text_field :name , label: "Nom"%>
    <% if(@sensor.sensor_type.nil?) %>
        <%= f.select :sensor_type_id, options_for_select(SensorType.all.map{|s|[s.name, s.id]}), label: "Type" %>
    <% else %>
        <%= f.select :sensor_type_id, options_for_select(SensorType.all.map{|s|[s.name, s.id]}, @sensor.sensor_type.id), label: "Type" %>
    <% end %>
    <a onclick="$('#modalSensorType').modal()">
      Nouveau type de capteur
    </a>
    <% if(@sensor.arduino.nil?) %>
        <%= f.select :arduino_id, options_for_select(Arduino.all.map{|s|[s.name, s.id]}), label: "Arduino" %>
    <% else %>
        <%= f.select :arduino_id, options_for_select(Arduino.all.map{|s|[s.name, s.id]}, @sensor.arduino.id), label: "Arduino"%>
    <% end %>
    <a onclick="$('#modalArduino').modal()">
      Nouvelle arduino
    </a>
    <%= f.number_field :serial, label: "Serial number"%>
    <%= f.submit %>
<% end %>

<% if can? :create, SensorType %>
    <!-- Modal-->
    <div class="modal fade" id="modalSensorType" tabindex="-1" role="dialog" aria-labelledby="modalSensorTypeLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="modalSensorTypeLabel">Nouveau type de capteur</h4>
          </div>
          <div class="modal-body">
            <% sensor_type = SensorType.new %>
            <%= bootstrap_form_for(sensor_type) do |f| %>
                <%= f.text_field :name, label: "Nom" %>
                <%= f.text_field :unit, label: "Unité"  %>
                <%= f.file_field :image , label: "Image"  %>
                <%= f.check_box :remove_image , label: "Supprimer l'image"  %>
                <%= f.submit %>
            <% end %>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
          </div>
        </div>
      </div>
    </div>
<% end %>

<% if can? :create, Arduino %>
    <!-- Modal-->
    <div class="modal fade" id="modalArduino" tabindex="-1" role="dialog" aria-labelledby="modalArduinoLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="modalArduinoLabel">Nouvelle arduino</h4>
          </div>
          <div class="modal-body">
            <% arduino = Arduino.new %>
            <%= bootstrap_form_for(arduino) do |f| %>
                <%= f.text_field :name , label: "Nom"%>
                <%= f.select :hive_id, options_for_select(Hive.all.map{|s|[s.name, s.id]}), label: "Ruche" %>
                <%= f.number_field :serial, label: "Serial number"%>
                <%= f.submit %>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/sensors/compare.erb
<%= @test %>
<p id="notice"><%= notice %></p>

<%= high_chart("high_chart", @chart) %>
<%= link_to 'Retour', :back %>

app/views/sensors/edit.html.erb
<h1>Editer capteur</h1>

<%= render 'form' %>

<%= link_to 'Voir', @sensor %> |
<%= link_to 'Retour', :back %>

app/views/sensors/index.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h2 class="section-heading">Liste des capteurs</h2>
    <h3 class="section-subheading text-muted">Capteurs montés sur les ruches</h3>
  </div>
</div>

<br>
<br>

<!-- AFFICHAGES DES SENSORS -->
<div class="row placeholders">
  <% @sensors.each do |sensor| %>
      <% if can? :update, sensor %>
      <!-- Modal-->
      <div class="modal fade" id="modalSensor<%= sensor.id %>" tabindex="-1" role="dialog" aria-labelledby="modalSensorLabel<%= sensor.id %>" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="modalSensorLabel<%= sensor.id %>">Editer capteur</h4>
            </div>
            <div class="modal-body">
              <%= bootstrap_form_for(sensor) do |f| %>
                  <% if sensor.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

                        <ul>
                          <% sensor.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                          <% end %>
                        </ul>
                      </div>
                  <% end %>
                  <%= f.text_field :name , label: "Nom"%>
                  <% if(sensor.sensor_type.nil?) %>
                      <%= f.select :sensor_type_id, options_for_select(SensorType.all.map{|s|[s.name, s.id]}), label: "Type" %>
                  <% else %>
                      <%= f.select :sensor_type_id, options_for_select(SensorType.all.map{|s|[s.name, s.id]}, sensor.sensor_type.id), label: "Type" %>
                  <% end %>
                  <% if(sensor.arduino.nil?) %>
                      <%= f.select :arduino_id, options_for_select(Arduino.all.map{|s|[s.name, s.id]}), label: "Arduino" %>
                  <% else %>
                      <%= f.select :arduino_id, options_for_select(Arduino.all.map{|s|[s.name, s.id]}, sensor.arduino.id), label: "Arduino"%>
                  <% end %>
                  <%= f.submit %>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <div class="eq-col-xs-12 col-sm-4 col-lg-3 tileContainer tileEffect">
        <div class="col-xs-12 tile">
          <div class="col-xs-8">
            <%= link_to image_tag(sensor.sensor_type.image, :class=>'iconEffect iconEffectNoZoom img-responsive'), sensor %>
          </div>
          <div class="col-xs-4 text-right" style="padding:0">
            <div class="col-xs-12"><%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-search glyphicon-change'), sensor %></div>
            <% if can? :update, sensor %>
            <div class="col-xs-12">
              <a onclick="$('#modalSensor<%= sensor.id %>').modal()">
                <span class="iconEffect glyphicon glyphicon-pencil glyphicon-change" aria-hidden="true"></span>
              </a>
            </div>
            <% end %>
            <% if can? :delete, sensor %>
            <div class="col-xs-12"><%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-remove glyphicon-change'), sensor, method: :delete, data: { confirm: 'Etes-vous sûr?' } %></div>
            <% end %>
          </div>
          <div class="col-xs-8">
            <b><%= sensor.name %> :</b>
          </div>
          <div class="col-xs-4">
            <% if sensor.datum.last().nil? %>
                #
            <% else %>
                <%= sensor.datum.last().value %><%= sensor.sensor_type.unit %>
            <% end %>
          </div>
          <div class="col-xs-8">
            <b>Comparer</b>
          </div>
          <div class="col-xs-4">
            <input type="checkbox" class="compareSensor" data-id="<%= sensor.id %>"/>
          </div>
          <% if can? :update, sensor %>
              <div class="col-xs-8">
                <b>Serial :</b>
              </div>
              <div class="col-xs-4">
                <%= sensor.serial %>
              </div>
          <% end %>
        </div>
      </div>
  <% end %>
  <% if can? :create, Sensor %>
  <div class="col-xs-12 col-sm-5 col-md-3 col-lg-2 tileContainer tileEffect">
    <div class="col-xs-12 tile">
      <div class="col-xs-8">
        <%= image_tag 'capteur.png', :class=>'img-responsive' %>
      </div>
      <div class="col-xs-4 text-right" style="padding:0">
        <div class="col-xs-12"><%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-plus glyphicon-change'), new_sensor_path %></div>
      </div>
      <div class="col-xs-12">
        <b>Emplacement disponible</b>
      </div>
    </div>
  </div>
  <% end %>
</div>

<% if @sensors.size > 0 %>
    <input type="submit" class="btn btn-success" value="Comparer"/>
<% end %>

<script>
    $("input[type=submit]").click(function(){
        var compare = {};
        compare.sensors = [];
        compare['<%= request_forgery_protection_token.to_s %>'] = "<%= form_authenticity_token %>";
        $(".compareSensor").each(function(){
            if($(this).prop('checked'))
            {
                compare.sensors.push($(this).attr("data-id"));
            }
        });
        if(compare.sensors.length > 0)
        {
            $.form("<%= url_for :controller => 'sensors', :action => 'compare' %>", compare, 'POST').submit();
        }
    })
</script>

app/views/sensors/index2.erb
<h1>Listing capteurs</h1>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Nom</th>
    <th>Type</th>
    <th>Arduino</th>
    <th>Serial</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.name %></td>
        <td><%= sensor.sensor_type.name %></td>
        <td><%= sensor.arduino.name if sensor.arduino %></td>
        <td><%= sensor.serial %></td>
        <td><%= link_to 'Voir', sensor %></td>
        <td><%= link_to 'Editer', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Supprimer', sensor, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau capteur', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>Nouveau capteur</h1>

<%= render 'form' %>

<%= link_to 'Retour', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<%= high_chart("high_chart", @chart) %>
<%= link_to 'Retour', :back %>