config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :arduinos

  resources :data

  resources :sensor_types

  post 'sensors/compare' => 'sensors#compare'
  resources :sensors

  resources :hives

  devise_for :users #enable registration

  namespace :admin do
    get '', to: 'admin#index', as: '/'
    resources :users
  end

  scope '/admin' do
    get 'sensors' => 'sensors#index2'
    get 'hives' => 'hives#index2'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get '/:hive_name' => 'hives#show'

  root to: 'hives#index'

end

app/models/hive.rb
class Hive < ActiveRecord::Base
	has_many :arduinos
	validates :name,  presence: true
	validates :name, uniqueness: true
end

app/controllers/hives_controller.rb
# encoding: utf-8
class HivesController < ApplicationController
  load_and_authorize_resource
  before_action :set_hive, only: [:show, :edit, :update, :destroy]

  # GET /hives
  # GET /hives.json
  def index
    @hives = Hive.all
    # State of the hives
    @hiveState = {}

    # For each hive
    @hives.each do |hive|
      # Create a list of all sensors
      sensors = []
      # For each arduino of the hive
      hive.arduinos.each do |arduino|
        # For each sensor of the arduino
        arduino.sensors.each do |sensor|
          # Add it to the list
          sensors.push(sensor)
        end
      end

      # Default state
      updatedRecently = true if sensors.size > 0

      # Retrieve time
      @tRef = Time.now
      # For each sensor
      sensors.each do |sensor|
        # If there are no date or the data haven't been updated since one hour
        if sensor.datum.size == 0 || (@tRef - sensor.datum.order('created_at ASC').all.last.created_at) > 25.hours
          updatedRecently = false
          break
        end

      end
      # Push it to the associative array
      @hiveState[hive.id] = updatedRecently
    end
  end

  def index2
    @hives = Hive.all
  end

  # GET /hives/1
  # GET /hives/1.json
  def show
    @hive
    # State of the sensor
    @sensorState = {}

    # Create a list of all sensors
    sensors = []
    # For each arduino of the hive
    @hive.arduinos.each do |arduino|
      # For each sensor of the arduino
      arduino.sensors.each do |sensor|
        # Add it to the list
        sensors.push(sensor)
      end
    end


    # Retrieve time
    @tRef = Time.now
    # For each sensor
    sensors.each do |sensor|
      # Default state
      updatedRecently = true
      # If there are no date or the data haven't been updated since one hour
      if sensor.datum.size == 0 || (@tRef - sensor.datum.order('created_at ASC').all.last.created_at) > 25.hours
        updatedRecently = false
      end

      # Push it to the associative array
      @sensorState[sensor.id] = updatedRecently
    end
  end

  # GET /hives/new
  def new
    @hive = Hive.new
  end

  # GET /hives/1/edit
  def edit
  end

  # POST /hives
  # POST /hives.json
  def create
    @hive = Hive.new(hive_params)

    respond_to do |format|
      if @hive.save
        format.html { redirect_to :back, notice: 'Ruche créée avec succès.' }
        format.json { render :show, status: :created, location: @hive }
      else
        format.html { render :new }
        format.json { render json: @hive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hives/1
  # PATCH/PUT /hives/1.json
  def update
    respond_to do |format|
      if @hive.update(hive_params)
        format.html { redirect_to :back, notice: 'Ruche mise à jour avec succès.' }
        format.json { render :show, status: :ok, location: @hive }
      else
        format.html { render :edit }
        format.json { render json: @hive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hives/1
  # DELETE /hives/1.json
  def destroy
    @hive.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Ruche supprimée avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hive
      if(!params[:hive_name].nil?)
        @hive = Hive.where(name: params[:hive_name]).first
        if(@hive.blank?)
            redirect_to action: "index"
        end
      else
        @hive = Hive.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hive_params
      params.require(:hive).permit(:name)
    end
end

app/helpers/hives_helper.rb
module HivesHelper
end

app/views/hives/_form.html.erb
<%= bootstrap_form_for(@hive) do |f| %>
    <%= f.text_field :name, label: "Nom" %>
    <%= f.submit %>
<% end %>

app/views/hives/edit.html.erb
<h1>Editer ruche</h1>

<%= render 'form' %>

<%= link_to 'Voir', @hive %> |
<%= link_to 'Retour', :back %>

app/views/hives/index.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h2 class="section-heading">Liste des ruches</h2>
    <h3 class="section-subheading text-muted">Ruches connectées au système</h3>
  </div>
</div>

<br>
<br>

<!-- AFFICHAGES DES RUCHES -->
<div class="row placeholders">
  <% @hives.each do |hive| %>
      <div class="eq-col-xs-12 col-sm-6 col-md-4 col-lg-3 tileContainer tileEffect">
        <div class="col-xs-12 tile">
          <div class="working-state-indicator <%= @hiveState[hive.id] ? 'green-indicator' : 'red-indicator' %>"></div>
          <div class="col-xs-8">
            <%= link_to image_tag('ruche-flat.png', :class=>'iconEffect iconEffectNoZoom img-responsive'), hive %>
          </div>
          <div class="col-xs-4 text-right" style="padding:0">
            <div class="col-xs-12"><%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-search glyphicon-change'), hive %></div>
            <% if can? :update, hive %>
                <div class="col-xs-12">
                  <a onclick="$('#modal<%= hive.id %>').modal()">
                    <span class="iconEffect glyphicon glyphicon-pencil glyphicon-change" aria-hidden="true"></span>
                  </a>
                </div>
            <% end %>
            <% if can? :delete, hive %>
                <div class="col-xs-12">
                  <%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-remove glyphicon-change'), hive, method: :delete, data: { confirm: 'Etes-vous sûr?' } %>
                </div>
                <!-- Button trigger modal-->
            <% end %>
          </div>
          <div class="col-xs-12">
            <b><%= hive.name %></b>
          </div>
        </div>
      </div>
      <% if can? :update, hive %>
          <!-- Modal-->
          <div class="modal fade" id="modal<%= hive.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel<%= hive.id %>" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                  <h4 class="modal-title" id="modalLabel<%= hive.id %>">Editer ruche</h4>
                </div>
                <div class="modal-body">
                  <%= bootstrap_form_for(hive) do |f| %>
                      <% if hive.errors.any? %>
                          <div id="error_explanation">
                            <h2><%= pluralize(hive.errors.count, "error") %> prohibited this hive from being saved:</h2>
                            <ul>
                              <% hive.errors.full_messages.each do |message| %>
                                  <li><%= message %></li>
                              <% end %>
                            </ul>
                          </div>
                      <% end %>
                      <%= f.text_field :name, label: "Nom" %>
                      <%= f.submit %>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                </div>
              </div>
            </div>
          </div>
      <% end %>
  <% end %>
  <% if can? :create, Hive %>
  <div class="col-xs-12 col-sm-5 col-md-3 col-lg-2 tileContainer tileEffect">
    <div class="col-xs-12 tile">
      <div class="col-xs-8">
        <%= image_tag 'ruche-flat.png', :class=>'img-responsive' %>
      </div>
      <div class="col-xs-4  text-right" style="padding:0">
        <div class="col-xs-12"><%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-plus glyphicon-change'), new_hive_path %></div>
      </div>
      <div class="col-xs-12">
          <b>Emplacement disponible</b>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/hives/index2.erb
<h1>Listing ruches</h1>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Nom</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @hives.each do |hive| %>
      <tr>
        <td><%= hive.name %></td>
        <td><%= link_to 'Voir', hive %></td>
        <td><%= link_to 'Editer', edit_hive_path(hive) %></td>
        <td><%= link_to 'Supprimer', hive, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle ruche', new_hive_path %>

app/views/hives/new.html.erb
<h1>Nouvelle ruche</h1>

<%= render 'form' %>

<%= link_to 'Retour', hives_path %>

app/views/hives/show.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h2 class="section-heading"><%= @hive.name %></h2>
  </div>
</div>
<br>
<br>
<p id="notice"><%= notice %></p>
<div class="row placeholders">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4 col-lg-offset-0">
    <%= image_tag 'ruche-flat.png', :class=> 'img-responsive' %>
    <div>
      <h3>Ruche <%= @hive.name %></h3>
      <!-- Button trigger modal-->
      <% if can? :update, @hive %>
      <a onclick="$('#modal<%= @hive.id %>').modal()">
        Editer
      </a>
      <% end %>
      <!-- Modal-->
      <div class="modal fade" id="modal<%= @hive.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel<%= @hive.id %>" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="modalLabel<%= @hive.id %>">Editer ruche</h4>
            </div>
            <div class="modal-body">
              <%= render 'form' %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-lg-8">
    <div class="col-xs-12">
      <h3>Liste des capteurs</h3>
    </div>
    <% @hive.arduinos.each do |arduino| %>
        <% arduino.sensors.each do |sensor| %>
      <div class="eq-col-xs-12 col-sm-6 col-md-4 col-lg-3 tileContainer tileEffect">
        <div class="col-xs-12 tile">
          <div class="working-state-indicator <%= @sensorState[sensor.id] ? 'green-indicator' : 'red-indicator' %>"></div>
            <div class="col-xs-8">
              <%= link_to image_tag(sensor.sensor_type.image, :class=>'iconEffect iconEffectNoZoom img-responsive'), sensor %>
            </div>
            <div class="col-xs-4  text-right" style="padding:0">
              <div class="col-xs-12"><%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-search glyphicon-change'), sensor %></div>
              <% if can? :update, sensor %>
              <div class="col-xs-12">
                <a onclick="$('#modalSensor<%= sensor.id %>').modal()">
                  <span class="iconEffect glyphicon glyphicon-pencil glyphicon-change" aria-hidden="true"></span>
                </a>
              </div>
              <% end %>
              <% if can? :delete, sensor %>
              <div class="col-xs-12"><%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-remove glyphicon-change'), sensor, method: :delete, data: { confirm: 'Etes-vous sûr?' } %></div>
              <% end %>
            </div>
            <div class="col-xs-8">
              <b><%= sensor.name %> :</b>
            </div>
            <div class="col-xs-4">
              <% if sensor.datum.last().nil? %>
                #
              <% else %>
                  <%= sensor.datum.last().value %><%= sensor.sensor_type.unit %>
              <% end %>
            </div>
          <div class="col-xs-8">
            <b>Comparer</b>
          </div>
          <div class="col-xs-4">
            <input type="checkbox" class="compareSensor" data-id="<%= sensor.id %>"/>
          </div>
          <% if can? :update, sensor %>
              <div class="col-xs-8">
                <b>Serial :</b>
              </div>
              <div class="col-xs-4">
                <%= sensor.serial %>
              </div>
          <% end %>
        </div>
      </div>
        <% if can? :update, sensor %>
            <!-- Modal-->
            <div class="modal fade" id="modalSensor<%= sensor.id %>" tabindex="-1" role="dialog" aria-labelledby="modalSensorLabel<%= sensor.id %>" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="modalSensorLabel<%= sensor.id %>">Editer capteur</h4>
                  </div>
                  <div class="modal-body">
                    <%= bootstrap_form_for(sensor) do |f| %>
                        <% if sensor.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

                              <ul>
                                <% sensor.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                <% end %>
                              </ul>
                            </div>
                        <% end %>
                        <%= f.text_field :name , label: "Nom"%>
                        <% if(sensor.sensor_type.nil?) %>
                            <%= f.select :sensor_type_id, options_for_select(SensorType.all.map{|s|[s.name, s.id]}), label: "Type" %>
                        <% else %>
                            <%= f.select :sensor_type_id, options_for_select(SensorType.all.map{|s|[s.name, s.id]}, sensor.sensor_type.id), label: "Type" %>
                        <% end %>
                        <% if(sensor.arduino.nil?) %>
                            <%= f.select :arduino_id, options_for_select(Arduino.all.map{|s|[s.name, s.id]}), label: "Arduino" %>
                        <% else %>
                            <%= f.select :arduino_id, options_for_select(Arduino.all.map{|s|[s.name, s.id]}, sensor.arduino.id), label: "Arduino"%>
                        <% end %>
                        <%= f.number_field :serial, label: "Serial number"%>
                        <%= f.submit %>
                    <% end %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      <% end %>
    <% end %>
    <% if can? :create, Sensor %>
    <div class="col-xs-12 col-sm-5 col-md-3 col-lg-2 tileContainer tileEffect">
      <div class="col-xs-12 tile">
        <div class="col-xs-8">
          <%= image_tag 'capteur.png', :style=>'width:100%' %>
        </div>
        <div class="col-xs-4  text-right" style="padding:0">
          <div class="col-xs-12"><%= link_to content_tag(:span, '', :class => 'iconEffect glyphicon glyphicon-plus glyphicon-change'), new_sensor_path %></div>
        </div>
        <div class="col-xs-12">
          <b>Emplacement disponible</b>
        </div>
      </div>
    </div>
    <% end %>
    <div class="col-xs-12">
      <%
         sensors = []
         @hive.arduinos.each do |arduino|
           arduino.sensors.each do |sensor|
             sensors.push(sensor)
           end
         end
         if sensors.size > 0 %>
          <input type="submit" class="btn btn-success" value="Comparer"/>
      <% end %>
    </div>
  </div>
</div>
<p>

</p>
<%= link_to 'Retour', :back %>

<script>
    $("input[type=submit]").click(function(){
        var compare = {};
        compare.sensors = [];
        compare['<%= request_forgery_protection_token.to_s %>'] = "<%= form_authenticity_token %>";
        $(".compareSensor").each(function(){
            if($(this).prop('checked'))
            {
                compare.sensors.push($(this).attr("data-id"));
            }
        });
        if(compare.sensors.length > 0)
        {
            $.form("<%= url_for :controller => 'sensors', :action => 'compare' %>", compare, 'POST').submit();
        }
    })
</script>