config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  resources :arduinos

  resources :data

  resources :sensor_types

  post 'sensors/compare' => 'sensors#compare'
  resources :sensors

  resources :hives

  devise_for :users #enable registration

  namespace :admin do
    get '', to: 'admin#index', as: '/'
    resources :users
  end

  scope '/admin' do
    get 'sensors' => 'sensors#index2'
    get 'hives' => 'hives#index2'
  end

  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get '/:hive_name' => 'hives#show'

  root to: 'hives#index'

end

app/views/admin/admin/index.html.erb
<div class="col-xs-12">
  <div class="col-xs-12">
    <h2>Zone administration</h2>
  </div>
  <!-- ZONE USER -->
  <div class="eq-col-xs-12 col-sm-4 col-lg-3 tileContainer tileEffect">
    <div class="col-xs-12 tile">
      <div class="col-xs-12">
        <%= link_to image_tag('users.png', :class=>'iconEffect', :style=>'padding:2px;width:60%'), admin_users_path %>
      </div>
      <div class="col-xs-12">
        <b>Gestion des utilisateurs</b>
      </div>
    </div>
  </div>


  <!-- ZONE SENSOR TYPE -->
  <div class="eq-col-xs-12 col-sm-4 col-lg-3 tileContainer tileEffect">
    <div class="col-xs-12 tile">
      <div class="col-xs-12">
        <%= link_to image_tag('engrenage.png', :class=>'iconEffect', :style=>'padding:2px;width:60%'), sensor_types_path %>
      </div>
      <div class="col-xs-12">
        <b>Gestion des types de capteur</b>
      </div>
    </div>
  </div>



  <!-- ZONE ARDUINO -->
  <div class="eq-col-xs-12 col-sm-4 col-lg-3 tileContainer tileEffect">
    <div class="col-xs-12 tile">
      <div class="col-xs-12">
        <%= link_to image_tag('arduino.png', :class=>'iconEffect', :style=>'padding:2px;width:60%'), arduinos_path %>
      </div>
      <div class="col-xs-12">
        <b>Gestion des arduinos</b>
      </div>
    </div>
  </div>



  <!-- ZONE CAPTEURS -->
  <div class="eq-col-xs-12 col-sm-4 col-lg-3 tileContainer tileEffect">
    <div class="col-xs-12 tile">
      <div class="col-xs-12">
        <%= link_to image_tag('capteur.png', :class=>'iconEffect', :style=>'padding:2px;width:60%'), controller: '/sensors', action: 'index2' %>
      </div>
      <div class="col-xs-12">
        <b>Gestion des capteurs</b>
      </div>
    </div>
  </div>

  <!-- ZONE RUCHES -->
  <div class="eq-col-xs-12 col-sm-4 col-lg-3 tileContainer tileEffect">
    <div class="col-xs-12 tile">
      <div class="col-xs-12">
        <%= link_to image_tag('ruche-flat.png', :class=>'iconEffect', :style=>'padding:2px;width:60%'), controller: '/hives', action: 'index2' %>
      </div>
      <div class="col-xs-12">
        <b>Gestion des ruches</b>
      </div>
    </div>
  </div>
</div>